// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOxcdupn6Vn3Fhj3Drjk4WXvRSavSuuWM',
    appId: '1:137723142708:web:5e31bf5648fb8fb13da061',
    messagingSenderId: '137723142708',
    projectId: 'expert-system-3',
    authDomain: 'expert-system-3.firebaseapp.com',
    storageBucket: 'expert-system-3.firebasestorage.app',
    measurementId: 'G-3P5ZHJ1S2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyxNdLJ8zOICE_IOrcW8lPBJ2P4ipDTtg',
    appId: '1:137723142708:android:75580a4dfd5016e63da061',
    messagingSenderId: '137723142708',
    projectId: 'expert-system-3',
    storageBucket: 'expert-system-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzsPBFS18RYWp-R6WVD9xndaZ1MaoNOg',
    appId: '1:137723142708:ios:97449b3815f076743da061',
    messagingSenderId: '137723142708',
    projectId: 'expert-system-3',
    storageBucket: 'expert-system-3.firebasestorage.app',
    iosClientId: '137723142708-nkaba5a9r145ij1vqul75n835f116fvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
